### ISSUE TITLE
1695 segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by ChillarAnand** [TeluguOCR/banti_segmenter#2]
OCR is working very well with given sample data.

I tried to convert a test image and segmenter is throwing segmentation fault.

```
$ ./banti_segmenter ../ocr/biddala/0-007.converted.tif 
[1]    1695 segmentation fault (core dumped)  ./banti_segmenter ../ocr/biddala/0-007.converted.tif
```

Full trace:

```
# anand at anand in ~/projects/python/banti_telugu_ocr on git:master o [16:06:48]                                               [25/485]
$ python3  recognize.py ../ocr/biddala/0-007.png 
Command line Arguments
        banti_segmenter     ./banti_segmenter
        calibration         1
        input_file_or_dir   ../ocr/biddala/0-007.png
        labels_fname        labellings/alphacodes.lbl
        log_level           20
        ngram_fname         library/mega.123.pkl
        nnet_fname          library/nn.pkl
        scaler_fname        scalings/relative48.scl

Initializing the OCR
Compiling full test function...
Done
Launched command with timeout=10
"convert -units PixelsPerInch ../ocr/biddala/0-007.png -compress Group4 -depth 1 -resample 400 ../ocr/biddala/0-007.converted.tif"
Success
STDOUT:

STDERR:

Launched command with timeout=10
"./banti_segmenter ../ocr/biddala/0-007.converted.tif"
Success
STDOUT:

STDERR:

Launched command with timeout=10
"./banti_segmenter ../ocr/biddala/0-007.converted.tif"
Success
STDOUT:

STDERR:

Traceback (most recent call last):
  File "recognize.py", line 229, in <module>
    recognizer.ocr_box_file(box_fname)
  File "/home/anand/projects/python/banti_telugu_ocr/ocr.py", line 48, in ocr_box_file
    bf = BantryFile(box_fname)
  File "/home/anand/projects/python/banti_telugu_ocr/bantry.py", line 155, in __init__
    in_file = open(name)
FileNotFoundError: [Errno 2] No such file or directory: '../ocr/biddala/0-007.converted.box'
```

Image used

![0-007](https://cloud.githubusercontent.com/assets/4463796/12548801/d5f13fa2-c37e-11e5-9b12-ec0cf1b380bd.png)

**Comment by ChillarAnand** [comment]
`ulimit -s 1000000` this worked. Thank You.
